name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Run PR-CI
    runs-on: macOS-latest
    env:
      SCHEME: KarrotFlex
      SDK: iphonesimulator
      DESTINATION: platform=iOS Simulator,name=iPhone 13 Pro,OS=latest
  
    steps:
    - name: Checkout the Git repository
      uses: actions/checkout@v2

    - name: Build and Test
      run: |
        set -o pipefail && xcodebuild clean build test \
          -scheme "$SCHEME" \
          -sdk "$SDK" \
          -destination "$DESTINATION" \
          -configuration Debug \
          -enableCodeCoverage YES \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c;

    - name: Codecov
      uses: codecov/codecov-action@v2.1.0